name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.rs"

  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.rs"
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # Warningもエラーとして扱う
  RUSTFLAGS: "-Dwarnings"
  PKG_CONFIG_PATH: usr/lib/x86_64-linux-gnu/pkgconfig

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src-tauri

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        echo "deb http://archive.ubuntu.com/ubuntu focal-updates main" >> /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose
    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features
    - name: Check formatting
      run: cargo fmt --all --check

