name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.rs"

  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.rs"

env:
  CARGO_TERM_COLOR: always
  # Warningもエラーとして扱う
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src-tauri

    steps:
    - uses: actions/checkout@v4
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose
    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features
    - name: Check formatting
      run: cargo fmt --all --check

